## Import data

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('./6934_1593423955510.txt')

In [3]:
df.head(30)

,block1,,.1,Kadın,Erkek,1,img,/images/male-3.png,Target2,1450.774999999794,True
0,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,350.165,True
1,block1,,,Kadın,Erkek,1,img,/images/female-3.png,Target1,434.745,True
2,block1,,,Kadın,Erkek,1,img,/images/female-2.png,Target1,410.260,True
3,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,462.010,True
4,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,531.130,True
5,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,358.805,True
6,block1,,,Kadın,Erkek,1,img,/images/female-2.png,Target1,411.755,True
7,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,483.070,True
8,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,387.385,True
9,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,371.165,True
10,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,387.170,True
11,block1,,,Kadın,Erkek,1,img,/images/male-1.png,Target2,435.640,True
12,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,403.960,True
13,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,360.490,True
14,block1,,,Kadın,Erkek,1,img,/images/female-1.png,Target1,414.165,True
15,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,526.370,True
16,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,438.460,True
17,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,403.855,True
18,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,412.945,True
19,block2,İyi,Kötü,,,1,txt,Güvenilir,İyi,716.185,True
20,block2,İyi,Kötü,,,1,txt,Ağırbaşlı,İyi,404.495,True
21,block2,İyi,Kötü,,,1,txt,Alıngan,Kötü,589.235,True
22,block2,İyi,Kötü,,,1,txt,Cesur,İyi,594.205,True
23,block2,İyi,Kötü,,,1,txt,Çekingen,Kötü,733.145,False
24,block2,İyi,Kötü,,,1,txt,Çekingen,Kötü,373.215,True
25,block2,İyi,Kötü,,,1,txt,Duygusal,Kötü,521.560,True
26,block2,İyi,Kötü,,,1,txt,Dobra,İyi,754.375,True
27,block2,İyi,Kötü,,,1,txt,Dobra,İyi,382.160,True
28,block2,İyi,Kötü,,,1,txt,Hassas,Kötü,3015.860,True
29,block2,İyi,Kötü,,,1,txt,Kararsız,Kötü,581.760,True

In [5]:
df.isnull().sum().sum()

0

In [ ]:
#I checked out if any value is NaN

In [6]:
df.info

<bound method DataFrame.info of      block1         .1  Kadın  Erkek  1  img     /images/male-3.png   Target2  \
0    block1             Kadın  Erkek  1  img     /images/male-3.png   Target2
1    block1             Kadın  Erkek  1  img   /images/female-3.png   Target1
2    block1             Kadın  Erkek  1  img   /images/female-2.png   Target1
3    block1             Kadın  Erkek  1  img     /images/male-3.png   Target2
4    block1             Kadın  Erkek  1  img     /images/male-2.png   Target2
..      ...  ...   ...    ...    ... ..  ...                    ...       ...
198  block7  İyi  Kötü  Kadın  Erkek  0  txt                Alıngan      Kötü
199  block7  İyi  Kötü  Kadın  Erkek  0  img     /images/male-3.png   Target2
200  block7  İyi  Kötü  Kadın  Erkek  0  txt                 Hassas      Kötü
201  block7  İyi  Kötü  Kadın  Erkek  0  img   /images/female-1.png   Target1
202  block7  İyi  Kötü  Kadın  Erkek  0  txt                  Dobra       İyi

     1450.774999999794  True
0              350.165  True
1              434.745  True
2              410.260  True
3              462.010  True
4              531.130  True
..                 ...   ...
198            587.225  True
199            459.725  True
200            555.825  True
201            480.160  True
202            708.370  True

[203 rows x 11 columns]>

In [94]:
print('Ndim: {}'.format(df.ndim))
print('Shape: {}'.format(df.shape))
print('Size: {}'.format(df.size))
print('Columns: {}'.format(df.columns))

Ndim: 2
Shape: (203, 11)
Size: 2233
Columns: Index(['block1', ' ', ' .1', 'Kadın', 'Erkek', '1', 'img',
       ' /images/male-3.png', ' Target2', 'Reaction Time (milliseconds)',
       'Output'],
      dtype='object')

In [19]:
df.rename(columns={'1450.774999999794': 'Reaction Time (milliseconds)', 'True': 'Output'} , inplace=True)

In [ ]:
# I renamed the columns to see more clearly while i was working on dataset

In [258]:
df.block1.unique()

array(['block1', 'block2', 'block3', 'block4', 'block5', 'block6',
       'block7'], dtype=object)

In [20]:
block1 = df.loc[df['block1'] == 'block1']
block2 = df.loc[df['block1'] == 'block2']
block3 = df.loc[df['block1'] == 'block3']
block4 = df.loc[df['block1'] == 'block4']
block5 = df.loc[df['block1'] == 'block5']
block6 = df.loc[df['block1'] == 'block6']
block7 = df.loc[df['block1'] == 'block7']

In [ ]:
#as we can see, dataset which i worked includes 7 different blocks, this line divided my data into 7 parts

In [91]:
block1.head(10)

,block1,,.1,Kadın,Erkek,1,img,/images/male-3.png,Target2,Reaction Time (milliseconds),Output
0,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,350.165,True
1,block1,,,Kadın,Erkek,1,img,/images/female-3.png,Target1,434.745,True
2,block1,,,Kadın,Erkek,1,img,/images/female-2.png,Target1,410.260,True
3,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,462.010,True
4,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,531.130,True
5,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,358.805,True
6,block1,,,Kadın,Erkek,1,img,/images/female-2.png,Target1,411.755,True
7,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,483.070,True
8,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,387.385,True
9,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,371.165,True

In [60]:
result1 = block1[['Reaction Time (milliseconds)']].mean(axis=0)

In [ ]:
#this line calculate mean/average of a given column

In [64]:
RT1 = result1

In [65]:
RT1

Reaction Time (milliseconds)    420.186579
dtype: float64

In [93]:
block2.head(10)

,block1,,.1,Kadın,Erkek,1,img,/images/male-3.png,Target2,Reaction Time (milliseconds),Output
19,block2,İyi,Kötü,,,1,txt,Güvenilir,İyi,716.185,True
20,block2,İyi,Kötü,,,1,txt,Ağırbaşlı,İyi,404.495,True
21,block2,İyi,Kötü,,,1,txt,Alıngan,Kötü,589.235,True
22,block2,İyi,Kötü,,,1,txt,Cesur,İyi,594.205,True
23,block2,İyi,Kötü,,,1,txt,Çekingen,Kötü,733.145,False
24,block2,İyi,Kötü,,,1,txt,Çekingen,Kötü,373.215,True
25,block2,İyi,Kötü,,,1,txt,Duygusal,Kötü,521.560,True
26,block2,İyi,Kötü,,,1,txt,Dobra,İyi,754.375,True
27,block2,İyi,Kötü,,,1,txt,Dobra,İyi,382.160,True
28,block2,İyi,Kötü,,,1,txt,Hassas,Kötü,3015.860,True

In [53]:
block2ed = ~block2.apply(lambda series: series.astype(str).str.contains('False')).any(axis=1)

In [ ]:
#this line drop out Falses from specified block2 dataframe

In [54]:
result2= block2[block2ed]

In [95]:
result2.head(10)

,block1,,.1,Kadın,Erkek,1,img,/images/male-3.png,Target2,Reaction Time (milliseconds),Output
19,block2,İyi,Kötü,,,1,txt,Güvenilir,İyi,716.185,True
20,block2,İyi,Kötü,,,1,txt,Ağırbaşlı,İyi,404.495,True
21,block2,İyi,Kötü,,,1,txt,Alıngan,Kötü,589.235,True
22,block2,İyi,Kötü,,,1,txt,Cesur,İyi,594.205,True
24,block2,İyi,Kötü,,,1,txt,Çekingen,Kötü,373.215,True
25,block2,İyi,Kötü,,,1,txt,Duygusal,Kötü,521.560,True
26,block2,İyi,Kötü,,,1,txt,Dobra,İyi,754.375,True
27,block2,İyi,Kötü,,,1,txt,Dobra,İyi,382.160,True
28,block2,İyi,Kötü,,,1,txt,Hassas,Kötü,3015.860,True
29,block2,İyi,Kötü,,,1,txt,Kararsız,Kötü,581.760,True

In [58]:
RT2 = result2[['Reaction Time (milliseconds)']].mean(axis=0)

In [59]:
RT2

Reaction Time (milliseconds)    642.71125
dtype: float64

In [96]:
block3.head(10)

,block1,,.1,Kadın,Erkek,1,img,/images/male-3.png,Target2,Reaction Time (milliseconds),Output
41,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,1424.005,True
42,block3,İyi,Kötü,Kadın,Erkek,1,txt,Akıllı,İyi,526.855,True
43,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/male-2.png,Target2,473.315,True
44,block3,İyi,Kötü,Kadın,Erkek,1,txt,Hassas,Kötü,552.740,True
45,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,398.200,False
46,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,435.290,True
47,block3,İyi,Kötü,Kadın,Erkek,1,txt,Çekingen,Kötü,532.855,True
48,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-1.png,Target1,431.595,True
49,block3,İyi,Kötü,Kadın,Erkek,1,txt,Kaba,Kötü,474.625,False
50,block3,İyi,Kötü,Kadın,Erkek,1,txt,Kaba,Kötü,142.310,True

In [67]:
block3ed = ~block3.apply(lambda series: series.astype(str).str.contains('False')).any(axis=1)

In [68]:
result3= block3[block3ed]

In [97]:
result3.head(10)

,block1,,.1,Kadın,Erkek,1,img,/images/male-3.png,Target2,Reaction Time (milliseconds),Output
41,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,1424.005,True
42,block3,İyi,Kötü,Kadın,Erkek,1,txt,Akıllı,İyi,526.855,True
43,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/male-2.png,Target2,473.315,True
44,block3,İyi,Kötü,Kadın,Erkek,1,txt,Hassas,Kötü,552.740,True
46,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,435.290,True
47,block3,İyi,Kötü,Kadın,Erkek,1,txt,Çekingen,Kötü,532.855,True
48,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-1.png,Target1,431.595,True
50,block3,İyi,Kötü,Kadın,Erkek,1,txt,Kaba,Kötü,142.310,True
51,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-2.png,Target1,409.255,True
53,block3,İyi,Kötü,Kadın,Erkek,1,txt,Başarılı,İyi,314.070,True

In [70]:
RT3 = result3[['Reaction Time (milliseconds)']].mean(axis=0)

In [71]:
RT3

Reaction Time (milliseconds)    488.773
dtype: float64

In [98]:
block4.head(10)

,block1,,.1,Kadın,Erkek,1,img,/images/male-3.png,Target2,Reaction Time (milliseconds),Output
67,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/male-3.png,Target2,727.125,True
68,block4,İyi,Kötü,Kadın,Erkek,1,txt,Cesur,İyi,495.190,True
69,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-1.png,Target1,685.015,True
70,block4,İyi,Kötü,Kadın,Erkek,1,txt,Ağırbaşlı,İyi,718.590,True
71,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,448.345,True
72,block4,İyi,Kötü,Kadın,Erkek,1,txt,Akıllı,İyi,465.225,True
73,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/male-2.png,Target2,634.930,True
74,block4,İyi,Kötü,Kadın,Erkek,1,txt,Ağırbaşlı,İyi,446.110,True
75,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,432.905,True
76,block4,İyi,Kötü,Kadın,Erkek,1,txt,Alıngan,Kötü,472.020,True

In [73]:
block4ed = ~block4.apply(lambda series: series.astype(str).str.contains('False')).any(axis=1)

In [74]:
result4 = block4[block4ed]

In [99]:
result4.head(10)

,block1,,.1,Kadın,Erkek,1,img,/images/male-3.png,Target2,Reaction Time (milliseconds),Output
67,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/male-3.png,Target2,727.125,True
68,block4,İyi,Kötü,Kadın,Erkek,1,txt,Cesur,İyi,495.190,True
69,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-1.png,Target1,685.015,True
70,block4,İyi,Kötü,Kadın,Erkek,1,txt,Ağırbaşlı,İyi,718.590,True
71,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,448.345,True
72,block4,İyi,Kötü,Kadın,Erkek,1,txt,Akıllı,İyi,465.225,True
73,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/male-2.png,Target2,634.930,True
74,block4,İyi,Kötü,Kadın,Erkek,1,txt,Ağırbaşlı,İyi,446.110,True
75,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,432.905,True
76,block4,İyi,Kötü,Kadın,Erkek,1,txt,Alıngan,Kötü,472.020,True

In [76]:
RT4 = result4[['Reaction Time (milliseconds)']].mean(axis=0)

In [77]:
RT4

Reaction Time (milliseconds)    472.96425
dtype: float64

In [78]:
block5ed = ~block5.apply(lambda series: series.astype(str).str.contains('False')).any(axis=1)

In [79]:
result5 = block5[block5ed]

In [80]:
RT5 = result5[['Reaction Time (milliseconds)']].mean(axis=0)

In [81]:
RT5

Reaction Time (milliseconds)    461.06275
dtype: float64

In [83]:
block6ed = ~block6.apply(lambda series: series.astype(str).str.contains('False')).any(axis=1)

In [84]:
result6 = block6[block6ed]

In [85]:
RT6 = result6[['Reaction Time (milliseconds)']].mean(axis=0)

In [86]:
RT6

Reaction Time (milliseconds)    640.724
dtype: float64

In [87]:
block7ed = ~block7.apply(lambda series: series.astype(str).str.contains('False')).any(axis=1)

In [88]:
result7 = block7[block7ed]

In [89]:
RT7 = result7[['Reaction Time (milliseconds)']].mean(axis=0)

In [90]:
RT7

Reaction Time (milliseconds)    502.824625
dtype: float64

In [115]:
final_result = {'RT': [RT1, RT2, RT3, RT4, RT5, RT6, RT6]}

In [116]:
final_result

{'RT': [Reaction Time (milliseconds)    420.186579
  dtype: float64,
  Reaction Time (milliseconds)    642.71125
  dtype: float64,
  Reaction Time (milliseconds)    488.773
  dtype: float64,
  Reaction Time (milliseconds)    472.96425
  dtype: float64,
  Reaction Time (milliseconds)    461.06275
  dtype: float64,
  Reaction Time (milliseconds)    640.724
  dtype: float64,
  Reaction Time (milliseconds)    640.724
  dtype: float64]}

In [117]:
final_result_ = pd.DataFrame (final_result, columns = ['RT'])

In [ ]:
#this line creates dataframe from final results to get average of the RT's

In [123]:
av_RT = final_result_.mean()

In [124]:
final_result_2 = {'RT': [RT1, RT2, RT3, RT4, RT5, RT6, RT6,a v_RT]}

In [125]:
final_result_2

{'RT': [Reaction Time (milliseconds)    420.186579
  dtype: float64,
  Reaction Time (milliseconds)    642.71125
  dtype: float64,
  Reaction Time (milliseconds)    488.773
  dtype: float64,
  Reaction Time (milliseconds)    472.96425
  dtype: float64,
  Reaction Time (milliseconds)    461.06275
  dtype: float64,
  Reaction Time (milliseconds)    640.724
  dtype: float64,
  Reaction Time (milliseconds)    640.724
  dtype: float64,
  RT    538.16369
  dtype: float64]}

In [131]:
RT_df = pd.DataFrame.from_dict(final_result_2)

In [134]:
RT_df

                                                  RT
0  Reaction Time (milliseconds)    420.186579
dty...
1  Reaction Time (milliseconds)    642.71125
dtyp...
2  Reaction Time (milliseconds)    488.773
dtype:...
3  Reaction Time (milliseconds)    472.96425
dtyp...
4  Reaction Time (milliseconds)    461.06275
dtyp...
5  Reaction Time (milliseconds)    640.724
dtype:...
6  Reaction Time (milliseconds)    640.724
dtype:...
7                     RT    538.16369
dtype: float64

In [136]:
RT_df.to_csv(r'C:\Users\90505\Desktop\dataset2\RT_df.csv', index = False)

In [ ]:
#this line exports the dataframe to outside

In [138]:
df.head(50)

,block1,,.1,Kadın,Erkek,1,img,/images/male-3.png,Target2,Reaction Time (milliseconds),Output
0,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,350.165,True
1,block1,,,Kadın,Erkek,1,img,/images/female-3.png,Target1,434.745,True
2,block1,,,Kadın,Erkek,1,img,/images/female-2.png,Target1,410.260,True
3,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,462.010,True
4,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,531.130,True
5,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,358.805,True
6,block1,,,Kadın,Erkek,1,img,/images/female-2.png,Target1,411.755,True
7,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,483.070,True
8,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,387.385,True
9,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,371.165,True
10,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,387.170,True
11,block1,,,Kadın,Erkek,1,img,/images/male-1.png,Target2,435.640,True
12,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,403.960,True
13,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,360.490,True
14,block1,,,Kadın,Erkek,1,img,/images/female-1.png,Target1,414.165,True
15,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,526.370,True
16,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,438.460,True
17,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,403.855,True
18,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,412.945,True
19,block2,İyi,Kötü,,,1,txt,Güvenilir,İyi,716.185,True
20,block2,İyi,Kötü,,,1,txt,Ağırbaşlı,İyi,404.495,True
21,block2,İyi,Kötü,,,1,txt,Alıngan,Kötü,589.235,True
22,block2,İyi,Kötü,,,1,txt,Cesur,İyi,594.205,True
23,block2,İyi,Kötü,,,1,txt,Çekingen,Kötü,733.145,False
24,block2,İyi,Kötü,,,1,txt,Çekingen,Kötü,373.215,True
25,block2,İyi,Kötü,,,1,txt,Duygusal,Kötü,521.560,True
26,block2,İyi,Kötü,,,1,txt,Dobra,İyi,754.375,True
27,block2,İyi,Kötü,,,1,txt,Dobra,İyi,382.160,True
28,block2,İyi,Kötü,,,1,txt,Hassas,Kötü,3015.860,True
29,block2,İyi,Kötü,,,1,txt,Kararsız,Kötü,581.760,True
30,block2,İyi,Kötü,,,1,txt,Güvenilir,İyi,566.040,True
31,block2,İyi,Kötü,,,1,txt,Başarılı,İyi,452.240,True
32,block2,İyi,Kötü,,,1,txt,Kararsız,Kötü,484.915,True
33,block2,İyi,Kötü,,,1,txt,Ağırbaşlı,İyi,542.905,False
34,block2,İyi,Kötü,,,1,txt,Ağırbaşlı,İyi,311.360,True
35,block2,İyi,Kötü,,,1,txt,Ağırbaşlı,İyi,594.800,True
36,block2,İyi,Kötü,,,1,txt,Akıllı,İyi,478.315,True
37,block2,İyi,Kötü,,,1,txt,Kaba,Kötü,531.480,True
38,block2,İyi,Kötü,,,1,txt,Dedikoducu,Kötü,571.550,True
39,block2,İyi,Kötü,,,1,txt,Hassas,Kötü,447.015,True
40,block2,İyi,Kötü,,,1,txt,Dedikoducu,Kötü,483.460,True
41,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,1424.005,True
42,block3,İyi,Kötü,Kadın,Erkek,1,txt,Akıllı,İyi,526.855,True
43,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/male-2.png,Target2,473.315,True
44,block3,İyi,Kötü,Kadın,Erkek,1,txt,Hassas,Kötü,552.740,True
45,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,398.200,False
46,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,435.290,True
47,block3,İyi,Kötü,Kadın,Erkek,1,txt,Çekingen,Kötü,532.855,True
48,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-1.png,Target1,431.595,True
49,block3,İyi,Kötü,Kadın,Erkek,1,txt,Kaba,Kötü,474.625,False

## Filtering

In [164]:
df.columns = df.columns.str.replace('/images/male-3.png','X')

In [165]:
df

,block1,,.1,Kadın,Erkek,1,img,X,Target2,Reaction Time (milliseconds),Output
0,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,350.165,True
1,block1,,,Kadın,Erkek,1,img,/images/female-3.png,Target1,434.745,True
2,block1,,,Kadın,Erkek,1,img,/images/female-2.png,Target1,410.260,True
3,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,462.010,True
4,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,531.130,True
...,...,...,...,...,...,...,...,...,...,...,...
198,block7,İyi,Kötü,Kadın,Erkek,0,txt,Alıngan,Kötü,587.225,True
199,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/male-3.png,Target2,459.725,True
200,block7,İyi,Kötü,Kadın,Erkek,0,txt,Hassas,Kötü,555.825,True
201,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/female-1.png,Target1,480.160,True
202,block7,İyi,Kötü,Kadın,Erkek,0,txt,Dobra,İyi,708.370,True

In [169]:
df.columns

Index(['block1', ' ', ' .1', 'Kadın', 'Erkek', '1', 'img', ' X', ' Target2',
       'Reaction Time (milliseconds)', 'Output'],
      dtype='object')

In [170]:
df = df.rename(columns={' X': 'X'})

In [ ]:
#I got some errors because of the name of column,then i changed

In [171]:
df.columns

Index(['block1', ' ', ' .1', 'Kadın', 'Erkek', '1', 'img', 'X', ' Target2',
       'Reaction Time (milliseconds)', 'Output'],
      dtype='object')

In [172]:
df.X.unique()

array([' /images/male-3.png', ' /images/female-3.png',
       ' /images/female-2.png', ' /images/male-2.png',
       ' /images/male-1.png', ' /images/female-1.png', ' Güvenilir',
       ' Ağırbaşlı', ' Alıngan', ' Cesur', ' Çekingen', ' Duygusal',
       ' Dobra', ' Hassas', ' Kararsız', ' Başarılı', ' Akıllı', ' Kaba',
       ' Dedikoducu'], dtype=object)

In [ ]:
#this line controls the values on a specific column

In [175]:
df_gender = df.loc[df['X'].isin([' /images/male-3.png', ' /images/female-3.png',
       ' /images/female-2.png', ' /images/male-2.png',
       ' /images/male-1.png', ' /images/female-1.png'])]

In [176]:
df_gender

,block1,,.1,Kadın,Erkek,1,img,X,Target2,Reaction Time (milliseconds),Output
0,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,350.165,True
1,block1,,,Kadın,Erkek,1,img,/images/female-3.png,Target1,434.745,True
2,block1,,,Kadın,Erkek,1,img,/images/female-2.png,Target1,410.260,True
3,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,462.010,True
4,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,531.130,True
...,...,...,...,...,...,...,...,...,...,...,...
191,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/female-2.png,Target1,527.385,True
194,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/female-2.png,Target1,421.425,True
197,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/female-3.png,Target1,440.545,True
199,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/male-3.png,Target2,459.725,True
201,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/female-1.png,Target1,480.160,True

## Add a gender column

In [185]:
def get_gender(gender):
    return gender.split('/')[2].split('-')[0]
df_gender['Gender'] = df_gender['X'].apply(lambda x: get_gender(x))

D:\Users\90505\anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [ ]:
# this function picks the characters between second / to first -

In [188]:
df_gender

,block1,,.1,Kadın,Erkek,1,img,X,Target2,Reaction Time (milliseconds),Output,Gender
0,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,350.165,True,male
1,block1,,,Kadın,Erkek,1,img,/images/female-3.png,Target1,434.745,True,female
2,block1,,,Kadın,Erkek,1,img,/images/female-2.png,Target1,410.260,True,female
3,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,462.010,True,male
4,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,531.130,True,male
...,...,...,...,...,...,...,...,...,...,...,...,...
191,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/female-2.png,Target1,527.385,True,female
194,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/female-2.png,Target1,421.425,True,female
197,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/female-3.png,Target1,440.545,True,female
199,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/male-3.png,Target2,459.725,True,male
201,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/female-1.png,Target1,480.160,True,female

In [189]:
block1_2 = df_gender.loc[df_gender['block1'] == 'block1']
block2_2 = df_gender.loc[df_gender['block1'] == 'block2']
block3_2 = df_gender.loc[df_gender['block1'] == 'block3']
block4_2 = df_gender.loc[df_gender['block1'] == 'block4']
block5_2 = df_gender.loc[df_gender['block1'] == 'block5']
block6_2 = df_gender.loc[df_gender['block1'] == 'block6']
block7_2 = df_gender.loc[df_gender['block1'] == 'block7']

In [190]:
block1_2

,block1,,.1,Kadın,Erkek,1,img,X,Target2,Reaction Time (milliseconds),Output,Gender
0,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,350.165,True,male
1,block1,,,Kadın,Erkek,1,img,/images/female-3.png,Target1,434.745,True,female
2,block1,,,Kadın,Erkek,1,img,/images/female-2.png,Target1,410.260,True,female
3,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,462.010,True,male
4,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,531.130,True,male
5,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,358.805,True,male
6,block1,,,Kadın,Erkek,1,img,/images/female-2.png,Target1,411.755,True,female
7,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,483.070,True,male
8,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,387.385,True,male
9,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,371.165,True,male
10,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,387.170,True,male
11,block1,,,Kadın,Erkek,1,img,/images/male-1.png,Target2,435.640,True,male
12,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,403.960,True,male
13,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,360.490,True,male
14,block1,,,Kadın,Erkek,1,img,/images/female-1.png,Target1,414.165,True,female
15,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,526.370,True,male
16,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,438.460,True,male
17,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,403.855,True,male
18,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,412.945,True,male

In [197]:
block1_2ed = ~block1_2.apply(lambda series: series.astype(str).str.contains('False')).any(axis=1)

In [200]:
result1_2 = block1_2[block1_2ed]

In [205]:
result1_2.head(5)

,block1,,.1,Kadın,Erkek,1,img,X,Target2,Reaction Time (milliseconds),Output,Gender
0,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,350.165,True,male
1,block1,,,Kadın,Erkek,1,img,/images/female-3.png,Target1,434.745,True,female
2,block1,,,Kadın,Erkek,1,img,/images/female-2.png,Target1,410.260,True,female
3,block1,,,Kadın,Erkek,1,img,/images/male-3.png,Target2,462.010,True,male
4,block1,,,Kadın,Erkek,1,img,/images/male-2.png,Target2,531.130,True,male

In [202]:
RT1_2 = result1_2[['Reaction Time (milliseconds)']].mean(axis=0)

In [203]:
RT1_2

Reaction Time (milliseconds)    420.186579
dtype: float64

In [204]:
##block2'de cinsiyet değeri yoktu. o yüzden block2_2de değer bulamadık.

In [193]:
block3_2

,block1,,.1,Kadın,Erkek,1,img,X,Target2,Reaction Time (milliseconds),Output,Gender
41,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,1424.005,True,female
43,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/male-2.png,Target2,473.315,True,male
45,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,398.200,False,female
46,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,435.290,True,female
48,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-1.png,Target1,431.595,True,female
51,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-2.png,Target1,409.255,True,female
54,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,645.335,True,female
56,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-1.png,Target1,539.420,True,female
59,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-2.png,Target1,543.400,True,female
63,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/male-1.png,Target2,432.315,True,male
65,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/male-2.png,Target2,427.530,True,male

In [209]:
block3_2ed = ~block3_2.apply(lambda series: series.astype(str).str.contains('False')).any(axis=1)

In [210]:
result3_2 = block3_2[block3_2ed]

In [212]:
result3_2.head(5)

,block1,,.1,Kadın,Erkek,1,img,X,Target2,Reaction Time (milliseconds),Output,Gender
41,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,1424.005,True,female
43,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/male-2.png,Target2,473.315,True,male
46,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,435.290,True,female
48,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-1.png,Target1,431.595,True,female
51,block3,İyi,Kötü,Kadın,Erkek,1,img,/images/female-2.png,Target1,409.255,True,female

In [213]:
RT3_2 = result3_2[['Reaction Time (milliseconds)']].mean(axis=0)

In [214]:
RT3_2

Reaction Time (milliseconds)    576.146
dtype: float64

In [194]:
block4_2

,block1,,.1,Kadın,Erkek,1,img,X,Target2,Reaction Time (milliseconds),Output,Gender
67,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/male-3.png,Target2,727.125,True,male
69,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-1.png,Target1,685.015,True,female
71,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,448.345,True,female
73,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/male-2.png,Target2,634.930,True,male
75,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,432.905,True,female
77,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-1.png,Target1,417.950,True,female
79,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-2.png,Target1,399.140,True,female
81,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-2.png,Target1,375.100,True,female
83,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/male-2.png,Target2,437.785,True,male
85,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,491.900,True,female
87,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-2.png,Target1,519.245,False,female
88,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-2.png,Target1,280.820,True,female
90,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-1.png,Target1,403.055,True,female
92,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/male-3.png,Target2,522.010,True,male
94,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-1.png,Target1,563.145,False,female
95,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-1.png,Target1,327.285,True,female
98,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/male-2.png,Target2,469.475,True,male
100,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,453.575,True,female
103,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,610.365,True,female
106,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/male-3.png,Target2,480.000,True,male
108,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-2.png,Target1,482.480,True,female
110,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/male-1.png,Target2,449.600,True,male

In [217]:
block4_2ed = ~block4_2.apply(lambda series: series.astype(str).str.contains('False')).any(axis=1)

In [218]:
result4_2 = block4_2[block4_2ed]

In [220]:
result4_2.head(5)

,block1,,.1,Kadın,Erkek,1,img,X,Target2,Reaction Time (milliseconds),Output,Gender
67,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/male-3.png,Target2,727.125,True,male
69,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-1.png,Target1,685.015,True,female
71,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,448.345,True,female
73,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/male-2.png,Target2,634.930,True,male
75,block4,İyi,Kötü,Kadın,Erkek,1,img,/images/female-3.png,Target1,432.905,True,female

In [221]:
RT4_2 = result4_2[['Reaction Time (milliseconds)']].mean(axis=0)

In [222]:
RT4_2

Reaction Time (milliseconds)    476.443
dtype: float64

In [195]:
block5_2

,block1,,.1,Kadın,Erkek,1,img,X,Target2,Reaction Time (milliseconds),Output,Gender
113,block5,,,Kadın,Erkek,0,img,/images/male-2.png,Target2,1464.055,True,male
114,block5,,,Kadın,Erkek,0,img,/images/male-1.png,Target2,435.270,True,male
115,block5,,,Kadın,Erkek,0,img,/images/female-1.png,Target1,443.375,True,female
116,block5,,,Kadın,Erkek,0,img,/images/male-2.png,Target2,434.825,True,male
117,block5,,,Kadın,Erkek,0,img,/images/male-3.png,Target2,539.165,False,male
118,block5,,,Kadın,Erkek,0,img,/images/male-3.png,Target2,356.415,True,male
119,block5,,,Kadın,Erkek,0,img,/images/male-3.png,Target2,317.710,True,male
120,block5,,,Kadın,Erkek,0,img,/images/male-3.png,Target2,333.965,True,male
121,block5,,,Kadın,Erkek,0,img,/images/female-3.png,Target1,417.250,True,female
122,block5,,,Kadın,Erkek,0,img,/images/male-2.png,Target2,495.975,True,male
123,block5,,,Kadın,Erkek,0,img,/images/male-2.png,Target2,361.040,True,male
124,block5,,,Kadın,Erkek,0,img,/images/female-1.png,Target1,447.145,True,female
125,block5,,,Kadın,Erkek,0,img,/images/male-2.png,Target2,458.505,True,male
126,block5,,,Kadın,Erkek,0,img,/images/female-1.png,Target1,524.155,True,female
127,block5,,,Kadın,Erkek,0,img,/images/male-1.png,Target2,449.230,True,male
128,block5,,,Kadın,Erkek,0,img,/images/female-3.png,Target1,385.585,True,female
129,block5,,,Kadın,Erkek,0,img,/images/female-1.png,Target1,408.970,True,female
130,block5,,,Kadın,Erkek,0,img,/images/male-1.png,Target2,407.470,False,male
131,block5,,,Kadın,Erkek,0,img,/images/male-1.png,Target2,217.930,True,male
132,block5,,,Kadın,Erkek,0,img,/images/male-1.png,Target2,478.045,True,male
133,block5,,,Kadın,Erkek,0,img,/images/male-2.png,Target2,437.295,True,male
134,block5,,,Kadın,Erkek,0,img,/images/male-1.png,Target2,354.515,True,male

In [223]:
block5_2ed = ~block5_2.apply(lambda series: series.astype(str).str.contains('False')).any(axis=1)

In [224]:
result5_2 = block5_2[block5_2ed]

In [225]:
RT5_2 = result5_2[['Reaction Time (milliseconds)']].mean(axis=0)

In [226]:
RT5_2

Reaction Time (milliseconds)    461.06275
dtype: float64

In [196]:
block6_2

,block1,,.1,Kadın,Erkek,1,img,X,Target2,Reaction Time (milliseconds),Output,Gender
135,block6,İyi,Kötü,Kadın,Erkek,0,img,/images/male-1.png,Target2,943.815,True,male
137,block6,İyi,Kötü,Kadın,Erkek,0,img,/images/female-2.png,Target1,362.665,False,female
138,block6,İyi,Kötü,Kadın,Erkek,0,img,/images/female-2.png,Target1,335.890,True,female
140,block6,İyi,Kötü,Kadın,Erkek,0,img,/images/male-1.png,Target2,396.635,True,male
142,block6,İyi,Kötü,Kadın,Erkek,0,img,/images/female-3.png,Target1,604.230,True,female
144,block6,İyi,Kötü,Kadın,Erkek,0,img,/images/male-1.png,Target2,808.090,False,male
145,block6,İyi,Kötü,Kadın,Erkek,0,img,/images/male-1.png,Target2,1017.320,True,male
147,block6,İyi,Kötü,Kadın,Erkek,0,img,/images/male-2.png,Target2,515.870,True,male
149,block6,İyi,Kötü,Kadın,Erkek,0,img,/images/female-3.png,Target1,554.630,True,female
151,block6,İyi,Kötü,Kadın,Erkek,0,img,/images/female-2.png,Target1,448.035,True,female
153,block6,İyi,Kötü,Kadın,Erkek,0,img,/images/male-2.png,Target2,403.185,True,male
155,block6,İyi,Kötü,Kadın,Erkek,0,img,/images/female-3.png,Target1,517.515,True,female

In [227]:
block6_2ed = ~block6_2.apply(lambda series: series.astype(str).str.contains('False')).any(axis=1)

In [228]:
result6_2 = block6_2[block6_2ed]

In [229]:
RT6_2 = result6_2[['Reaction Time (milliseconds)']].mean(axis=0)

In [230]:
RT6_2

Reaction Time (milliseconds)    573.7125
dtype: float64

In [231]:
block7_2

,block1,,.1,Kadın,Erkek,1,img,X,Target2,Reaction Time (milliseconds),Output,Gender
157,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/male-1.png,Target2,837.300,True,male
159,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/female-3.png,Target1,472.220,True,female
161,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/male-3.png,Target2,464.985,True,male
163,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/male-1.png,Target2,587.320,True,male
165,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/female-2.png,Target1,505.570,True,female
167,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/male-2.png,Target2,371.280,False,male
168,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/male-2.png,Target2,221.345,True,male
171,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/male-2.png,Target2,424.025,True,male
173,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/male-1.png,Target2,413.680,True,male
175,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/male-1.png,Target2,371.180,True,male
177,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/male-2.png,Target2,351.105,True,male
180,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/female-1.png,Target1,493.355,True,female
182,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/male-1.png,Target2,532.575,True,male
184,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/male-1.png,Target2,438.465,True,male
186,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/female-1.png,Target1,478.385,True,female
189,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/female-3.png,Target1,463.790,True,female
191,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/female-2.png,Target1,527.385,True,female
194,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/female-2.png,Target1,421.425,True,female
197,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/female-3.png,Target1,440.545,True,female
199,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/male-3.png,Target2,459.725,True,male
201,block7,İyi,Kötü,Kadın,Erkek,0,img,/images/female-1.png,Target1,480.160,True,female

In [232]:
block7_2ed = ~block7_2.apply(lambda series: series.astype(str).str.contains('False')).any(axis=1)

In [233]:
result7_2 = block7_2[block7_2ed]

In [234]:
RT7_2 = result7_2[['Reaction Time (milliseconds)']].mean(axis=0)

In [235]:
RT7_2

Reaction Time (milliseconds)    469.227
dtype: float64

In [249]:
RT6_2

Reaction Time (milliseconds)    573.7125
dtype: float64

In [254]:
data_rt = {'RT':['RT1_2', 'RT2_2', 'RT3_2', 'RT4_2', 'RT5_2', 'RT6_2', 'RT7_2'], 'Milliseconds':[420.186579, 'imagenotfound', 576.146, 476.443, 461.06275, 573.7125, 469.227]}

In [255]:
result_df2 = pd.DataFrame(data_rt)

In [256]:
result_df2

      RT   Milliseconds
0  RT1_2        420.187
1  RT2_2  imagenotfound
2  RT3_2        576.146
3  RT4_2        476.443
4  RT5_2        461.063
5  RT6_2        573.712
6  RT7_2        469.227

In [257]:
result_df2.to_csv(r'C:\Users\90505\Desktop\dataset2\result_df2.csv', index = False)